### ISSUE TITLE
Umbrella issue for Chronos refactor to enable customized installation

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#3170]
This issue is a detailed plan to realize issue intel-analytics/analytics-zoo-internal#107 and decoupling the major function of Chronos with other BigDL components.

@shane-huang @yushan111 

Overall design strategy **[edited after discussion with Jason]**

- `Chronos` should stick to `nano` for single node acceleration when appropriate and be **self-contained** and able to complete most of its functionalities without any other dependencies (`ray`/`orca`).
- `Chronos` will rely on `orca`/`ray` for functionalities with distribution fashion (**will be reflected in the following tabel**).
- `Chronos` will contain a light-weighted inference installation strategy. (maybe not a new whl)
- `tensorflow` is not my first priority since tf2 is intel's AI strategy while `Chronos` has no tf2 model right now.

Here is a full functionality table (**will be updated**)

| installation status   | installation cmd                                      | `Chronos` | `nano` | `orca` | TSDataset | XShardsTSDataset | F/D/S\*(distributed=False) | F/D/S\*(distributed=True) | ONNX | Auto Model | AutoTSEstimator | TSPipeline |
| --------------------- | ----------------------------------------------------- | --------- | ------ | ------ | --------- | ---------------- | -------------------------- | ------------------------- | ---- | ---------- | --------------- | ---------- |
| chronos with nano\*\* | `pip install bigdl-chronos`; `pip install bigdl-nano` | ✔         | ✔      | ❌      | ✔         | ❌                | ✔                          | ✔(Pseudo distributed)     | ✔    | ❌          | ❌               | ✔          |
| full chronos          | `pip install bigdl-chronos[all]`                     | ✔         | ✔      | ✔      | ✔         | ✔                | ✔                          | ✔                         | ✔    | ✔          | ✔               | ✔          |

\* F/D/S means Forecaster/Detector/Simulators

\*\* This two version can be used as light-weighted inference install strategy.

To complete these, we mainly need these steps(can be done simultaneously)

- [x] intel-analytics/analytics-zoo#3171
- [x] intel-analytics/analytics-zoo-internal#534
- [x] intel-analytics/analytics-zoo-internal#532

**Comment by shane-huang** [comment]
Seperating pytorch and tensorflow installation seems only a valid request for inference with size concerns. And it seems to me the option should be with nano instead of chronos (e.g. seperate libs installation such as pytorch-lightening, IPEX, intel-tensorflow, etc. ).  So the install options can be simplified to train/nano[pytorch]/nano[tensorflow]. Further, as our pytorch support is much better and tensorflow layer is thin (correct me if i'm wrong), we can simplify it to **`nano`** （both py+tf) & **`[nano+tensorflow]`**. So the options could be changed to as below: 
     - `nano`
     - `nano (tensorflow-only)`
     - `nano + orca`
     - `nano + orca + ray`

**Comment by jason-dai** [comment]
How about:

- **chronos default**: nano+orca+pytorch
- **chronos[nano]** or **chronos[lite]**: nano+pytorch
- **chronos[automl]**: nano+orca+ray+pytorch
- **chronos[all]**: nano+orca+ray+pytorch+tf

**Comment by TheaperDeng** [comment]
I prefer to simplify them to 3 options

- chronos: nano+pytorch
- chronos[distributed]: nano+orca+pytorch
- chronos[all]: nano+orca+ray+pytorch

And once our tf support is enhanced, we may change the options. currently, if users want to use tf, we can let them install tf themselves now.

The other reason is that tf1 is conflict with pytorch-lightning on some dependencies which may cause "[dependency hell](https://pip.pypa.io/en/stable/topics/dependency-resolution/)".

nano+orca+pytorch will only support 2 more features than nano+pytorch
- XShardsTSDataset (experimental)
- Distributed Training (w/o ray backend, while ray backend is our recommeneded&default backend)

**Comment by jason-dai** [comment]
> I prefer to simplify them to 3 options
> 
> * chronos: nano+pytorch
> * chronos[distributed]: nano+orca+pytorch
> * chronos[all]: nano+orca+ray+pytorch
> 
> And once our tf support is enhanced, we may change the options. currently, if users want to use tf, we can let them install tf themselves now.
> 
> The other reason is that tf1 is conflict with pytorch-lightning on some dependencies which may cause "[dependency hell](https://pip.pypa.io/en/stable/topics/dependency-resolution/)".
> 
> nano+orca+pytorch will only support 2 more features than nano+pytorch
> 
> * XShardsTSDataset (experimental)
> * Distributed Training (w/o ray backend, while ray backend is our recommeneded&default backend)

The default should be distributed; a light version can be single node only.
