### ISSUE TITLE
Friesian TODO tasks

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#3629]
- [x] https://github.com/intel-analytics/BigDL/blob/branch-2.0/.github/workflows/style-check.yml Style check in GitHub
- [ ] Docker image add dockerfile analytics-zoo/friesian#171 @pinggao187 (initially tested, would finish the image after the release of bigdl2.0)
- [x] Update the recsys demo to bigdl API.
- [ ] Orca non-pip cannot find the so file: Unable to extract native library into a temporary file for non-pip install #3252 need to modify the jenkins job to add back -P linux once this issue has been fixed. [BIGDL-ORCA] Enable flexable libPath for non-pip user #3315 @leonardozcm This is actually an Orca issue, low priority, just put it here in case.

**Comment by pohanchi** [comment]
hi, still stuck on the flexible path for non-pip user, can merge it into main branch ?
