### ISSUE TITLE
Friesian Serving TODO list

### ISSUE THREAD

**Issue by cyita** [intel-analytics/BigDL#3642]
Documentation:

- [ ] Architecture of the serving pipelines
- [ ] Schema of the parquet files
- [ ] Schema of the redis tables and configs
- [ ] List of the services and their APIs

Demo:

- [ ] Multi-server demo (docker swarm)

Performance Test

- [ ] Scalability test
- [ ] 24c72g docker containers QPS 3000 candidates 200 user 1500w item 1000w ebd dim 50

Others:

- [ ] merge serving to Friesian and divide the jars
