### ISSUE TITLE
Upgrade ray to 1.9.0

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/BigDL#3709]
- [x] UT in orca
- [x] UT in Chronos
- [x] new Jenkins environment with upgraded ray (py36/py37/horovod)
- [x] Test on Jenkins (UT/example/apps/quickstarts) #3729 
- [x] orca install dependencies #3812
- [x] Chronos install dependencies #3812
- [x] Quick start updates
- [x] Documents (github.io, example readme, ...)

**Comment by yushan111** [comment]
Install dependencies that need to be upgraded:

- [ ] pandas >= 1.0.5
- [ ] aiohttp == 3.8.1, aync-timeout >= 4

**Comment by yushan111** [comment]
Note that python 3.7.0 and 3.7.1 may cause **Can't pickle function objects error on ray.init** ([Ray issue](https://github.com/ray-project/ray/issues/19938))

**Comment by yushan111** [comment]
Jenkins pre-test:

**Orca Ray**
http://10.112.231.51:18888/job/ZOO-PR-BigDL-Python-Spark-2.4-py36-ray/231/
http://10.112.231.51:18888/job/ZOO-PR-BigDL-Python-Spark-2.4-py37-ray/220/

**Orca Ray Horovod**
http://10.112.231.51:18888/job/ZOO-PR-BigDL-Python-Spark-2.4-py37-Horovod/253/
http://10.112.231.51:18888/job/ZOO-PR-BigDL-Python-Spark-3.1-py37-Horovod/281/
http://10.112.231.51:18888/job/ZOO-PR-BigDL-Python-ExampleTests-py37-ray-horovod-Spark3/206/

**Chronos Ray**

**Chronos Ray Horovod**

**Comment by yushan111** [comment]
In Ray 1.9.0, UT passed but example tests with Ray PyTorch Estimator hang or deadlock, when `num_workers!=0` in Pytorch Dataloader. 

https://github.com/intel-analytics/BigDL/blob/6adaef18ca21e14acc507822e06b0bc87dc8385c/python/orca/example/learn/pytorch/fashion_mnist/fashion_mnist.py#L50-L51

The detail logs are as below (I used CTRL+C in the end). It seems Ray fails to get result stats back after training 1 epoch.
```
(PytorchRayWorker pid=25307) INFO:bigdl.orca.learn.pytorch.torch_runner:Finished training epoch 1, stats on rank 0: {'epoch': 1, 'batch_count': 938, 'num_samples': 60000, 'train_loss': 1.8933767430305481, 'last_train_loss': 0.6069512963294983}
^C^CError in sys.excepthook:
Traceback (most recent call last):
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/ray/worker.py", line 1062, in custom_excepthook
    error_message = "".join(traceback.format_tb(tb))
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/traceback.py", line 57, in format_tb
    return extract_tb(tb, limit=limit).format()
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/traceback.py", line 357, in extract
    filename, lineno, name, lookup_line=False, locals=f_locals))
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/traceback.py", line 243, in __init__
    def __init__(self, filename, lineno, name, *, lookup_line=True,
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/pyspark/context.py", line 270, in signal_handler
    raise KeyboardInterrupt()
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/home/shan/sources/BigDL/python/orca/example/learn/pytorch/fashion_mnist/fashion_mnist_tmp.py", line 197, in <module>
    main()
  File "/home/shan/sources/BigDL/python/orca/example/learn/pytorch/fashion_mnist/fashion_mnist_tmp.py", line 181, in main
    stats = orca_estimator.fit(train_data_creator, epochs=epochs, batch_size=batch_size)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_ray_estimator.py", line 268, in fit
    info=info)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_ray_estimator.py", line 470, in _train_epochs
    success = check_for_failure(remote_worker_stats)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_ray_estimator.py", line 51, in check_for_failure
    finished, unfinished = ray.wait(unfinished)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/ray/worker.py", line 1891, in wait
    fetch_local,
  File "python/ray/_raylet.pyx", line 1367, in ray._raylet.CoreWorker.wait
  File "python/ray/_raylet.pyx", line 154, in ray._raylet.check_status
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/ray/node.py", line 987, in _kill_process_type
    wait=wait)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/ray/node.py", line 1039, in _kill_process_impl
    process.wait(timeout_seconds)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/subprocess.py", line 1647, in _wait
    time.sleep(delay)
  File "/home/shan/anaconda3/envs/ray-latest/lib/python3.7/site-packages/pyspark/context.py", line 270, in signal_handler
    raise KeyboardInterrupt()
KeyboardInterrupt
Stopping orca context
```

**Ray 1.8.0 works fine. We will change the Ray upgrade to 1.8.0.**

**Comment by yushan111** [comment]
There are more critical issues in Ray 1.8.0
1.  Segmentation Fault caused by memory leak. Related issue https://github.com/intel-analytics/BigDL/issues/3742. And the two [parameter_server examples](https://github.com/intel-analytics/BigDL/tree/branch-2.0/python/orca/example/ray_on_spark/parameter_server) in ray_on_spark fail every time. 
2.  Ray processes failed to start up, related issue https://github.com/intel-analytics/arda-docker/issues/555, https://github.com/ray-project/ray/issues/19834

**Comment by yushan111** [comment]
@jason-dai  
Is that ok if we upgrade to Ray 1.9.0 and we don't allow `num_workers > 0` in Pytorch Dataloader for now? 
I will try to reproduce in ray and report an issue. 
https://github.com/intel-analytics/BigDL/blob/6adaef18ca21e14acc507822e06b0bc87dc8385c/python/orca/example/learn/pytorch/fashion_mnist/fashion_mnist.py#L50-L51
