### ISSUE TITLE
Chronos: bigdl-chronos-lite development task list

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#3728]
- [x] Forecaster on Nano #3539 
- [ ] TSPipeline on Nano #3609 
- [ ] AutoProphet/AutoARIMA without Orca (Except auto tuning)
- [ ] Sort out other dependencies
- [ ] new setup-lite.py
- [ ] Validation job on Jenkins
- [ ] Release
