### ISSUE TITLE
Chronos: Enhancement Umbrella Issue

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#3853]
**These enhancements are not that *"Urgent"* and will be completed as regular development for Chronos gradually.**

- [ ] A more user-friendly [tutorial page](https://bigdl.readthedocs.io/en/latest/doc/Chronos/QuickStart/index.html) to help them solve practical problems
- [ ] Support data creator
- [ ] Add NAB metrics and other simple metrics to `chronos/metric/ad_metrics.py`.
- [ ] Add N-Beats and Informer .
- [ ] Add `forecaster.tune()` method and remove `AutoModel` from recommended API (TBD)
- [ ] Add `detector.tune()` method to support AutoML in Anomaly Detector. (TBD)
