### ISSUE TITLE
Support Ray Dataset input for Orca PyTorch Estimator.

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/BigDL#4185]
- [x] Support Ray Dataset Input for `estimator.fit`  #4152 
- [x] Support Ray Dataset Input for `evaluate` #4214 
- [x] Support Ray Dataset Input for `predict` #4220 
- [x] Add example (Data processed with Ray Dataset) https://github.com/intel-analytics/BigDL/pull/4362
