### ISSUE TITLE
Improve nano documentation (docstring)

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#4433]
## Proposal:

We should make sure all user-facing APIs have proper "docstring"s, so that we can automatically generate API docs on the documentation website.

### Specifically, we should make sure the following checks pass:

pydocstyle --ignore D104,D100,D212,D203,D401,D402 ${NANO_HOME}/bigdl/nano/tf
pydocstyle --ignore D104,D100,D212,D203,D401,D402 ${NANO_HOME}/bigdl/nano/pytorch

### Current passed directories
```
${NANO_HOME}/bigdl/nano/tf
${NANO_HOME}/bigdl/nano/pytorch/*.py
${NANO_HOME}/bigdl/nano/pytorch/optim/
${NANO_HOME}/bigdl/nano/pytorch/plugins/
```

### Todos

- [ ] ${NANO_HOME}/bigdl/nano/pytorch/vision
- [ ] ${NANO_HOME}/bigdl/nano/pytorch/trainer
- [ ] ${NANO_HOME}/bigdl/nano/pytorch/runtime_binding (not sure if this contains user-facing API. If not, maybe we move it to somewhere else; or rename it to something like "utils" and we will always ignore directory named "utils" )

### Tests
https://github.com/intel-analytics/BigDL/blob/main/python/nano/test/run-nano-codestyle-test.sh#L8-L11

**Comment by yangw1234** [comment]
@TheaperDeng @zhentaocc what do you think?

**Comment by zhentaocc** [comment]
-${NANO_HOME}/bigdl/nano/pytorch/runtime_binding, will be removed in the future.

+${NANO_HOME}/bigdl/nano/pytorch/lightning.py
