### ISSUE TITLE
brainMRI example TODO

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#4956]
- [x] Add bigdl backend; update readme
- [x] Add jenkins tests for three backends
- [x] Investigate and support customized metrics and add evaluate; add results in README
- [x] Change backend to ray
@ForJadeForest
