### ISSUE TITLE
Umbrella issue of Friesian features (update from time to time)

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#5000]
**[FeatureTable]**
- [ ] https://github.com/intel-analytics/BigDL/issues/4252
- [ ] https://github.com/intel-analytics/BigDL/issues/3599
- [ ] https://github.com/intel-analytics/BigDL/issues/3214
- [ ] https://github.com/intel-analytics/BigDL/issues/3215
- [ ] https://github.com/intel-analytics/BigDL/issues/3216
- [ ] https://github.com/intel-analytics/BigDL/issues/3217
- [ ] https://github.com/intel-analytics/BigDL/issues/5054
- [ ] https://github.com/intel-analytics/BigDL/issues/5053
- [ ] https://github.com/intel-analytics/BigDL/issues/3218 (may not need, can ignore)
- [ ] Other operations: [ColumnSimilarity](https://nvidia-merlin.github.io/NVTabular/main/generated/nvtabular.ops.ColumnSimilarity.html), [Normalize](https://nvidia-merlin.github.io/NVTabular/main/generated/nvtabular.ops.Normalize.html), [ListSlice](https://nvidia-merlin.github.io/NVTabular/main/generated/nvtabular.ops.ListSlice.html), etc. https://github.com/intel-analytics/BigDL/issues/5055
- [ ] Handle NLP input (word2vec, sentence2vec, node2vec)
- [ ] Handle image input

**[Training]**
- [ ] DeepRec integration
- [ ] Train on multiple targets
- [ ] RL
- [ ] AutoML

**[Serving]**
- [ ] Open source offline faiss (including brute force and approx search)
- [ ] https://github.com/intel-analytics/BigDL/issues/3642
- [ ] How to deploy serving more easily? e.g. using K8s?
- [ ] Multiple model support
- [ ] DAG and model ensemble
- [ ] Model update
- [ ] Feature update
- [x] Monitor real-time results and probably some visualization?
- [ ] A/B testing
- [ ] Add faiss binary to bigdl-core?
- [ ] PyTorch DIEN serving (use jep so that the latest pytorch whls and optimizations could be applied?)
- [ ] Reorganize Friesian pom dependencies - Divide nearline & serving jar

**[Demo]**
- [ ] Open source Recsys demo (including a script to generate some dummy data for convenience; fix figure issues; remove hdfs paths)
- [ ] Docker file to run the train demo?
- [ ] PyTorch DIEN demo
- [ ] Two tower train demo

**[Performance]**
- [ ] DIEN E2E inference and https://github.com/intel-analytics/BigDL/issues/5008
- [ ] Wide Deep on newest server

**[Customer issues]**
TBD

cc @jason-dai @cyita
