### ISSUE TITLE
Security Scan, TPP license scan checklist

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/BigDL#5033]
- [x] source code scan with snyk
     - [x] java/scala scan
     - [x] python scan
     - [x] license issue fix
- [x] binary scan with bdba
    - [x] scan and analysis
    - [x] critical/high vulnerability fix
    - [x] license issue fix 
- [x] third-party license/copyright management
    - [x] tpp license management
    - [x] copyright management
    - [x] bom list generation
- [x] process
    - [x] license scan with fossa
        - [x] github action
        - [x] github shield 
    - [x] snyk scan action
    - [x] bdba scan action
    - [x] notification
