### ISSUE TITLE
Friesian FeatureTable missing OPs

### ISSUE THREAD

**Issue by cyita** [intel-analytics/BigDL#5055]
Operations supported by NVTabular:
- [ ] Normalize (mean std, continuous columns)
- [x] NormalizeMinMax (min max method)
- [x] FillMedian (replaces missing values with the median value for the column)
- [x] ClipMax (may add to existing clip method)
- [ ] ColumnSimilarity (calculates the similarity between two columns using tf-idf, cosine or inner product as the distance metric)
- [x] DifferenceLag(partition_cols, shift, columns) (calculates the difference between two consecutive rows of the dataset)
- [x] Dropna (datafram dropna) (detects missing values, and filters out rows with null values)
- [x] Filter
- [x] JoinExternal (left & inner)
- [x] JoinGroupby (groups the data by the given categorical feature(s) and calculates the desired statistics of requested continuous features (along with the count of rows in each group))
- [x] LambdaOp (apply row level functions) e.g., `def transform_python_udf(self, in_col, out_col, udf_func)`
- [x] TargetEncoding 

**StatOperator**
- [x] gen_string_idx with more options (e.g., no freq_limit, bucketing, etc.)
- [x] Median (quantile)(calculates median of features)
- [x] MinMax (calculates min and max statistics of features)
- [x] GroupbyStatistics ("count", "sum", "mean", "std", "var", "min", "max")(uses groupby aggregation to determine the unique groups of a categorical feature and calculates the desired statistics of requested continuous features)
- [ ] Moments (calculates some of the statistics of features including mean, variance, standarded deviation, and count)

**TODO**
- [x] Check the updates of NVTabular
